#Server Port
server:
  port: 8081

#Database Credentials
spring:
  application:
    name: authservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDON_HOST}:${MYSQL_ADDON_PORT}/${MYSQL_ADDON_DB}?useSSL=false&serverTimeZone=UTC
    username: ${MYSQL_ADDON_USER}
    password: ${MYSQL_ADDON_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#Token Properties
jwt:
  secret: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  #  expiration: 3600000   # 1 hour
  expiration: 300000 # 5 mins
#  expiration: 60000 # 1 mins
