#Server Port
#server:
#  port: 8081
server:
  port=${PORT:8080}:

#Database Credentials
spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Token Properties
jwt:
  secret: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
#  expiration: 3600000   # 1 hour
  expiration: 300000 # 5 mins
#  expiration: 60000 # 1 mins
logging:
  level:
    org:
      springframework:
      security: DEBUG

#springdoc:
#  swagger-ui:
#    operationsSorter: method
#    tagsSorter: alpha