#Server Port
server:
  port: 8081
#server:
#  port=${PORT:8080}:

#Database Credentials
spring:
  application:
    name: authservice
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

#Token Properties
jwt:
  secret: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
#  expiration: 3600000   # 1 hour
  expiration: 300000 # 5 mins
#  expiration: 60000 # 1 mins
logging:
  level:
    org:
      springframework:
      security: DEBUG

#springdoc:
#  swagger-ui:
#    operationsSorter: method
#    tagsSorter: alpha