#Server Port
server:
  port: ${PORT:8080}

#Database Credentials
spring:
  application:
    name: authservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

#Token Properties
jwt:
  secret: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  expiration: 300000 # 5 mins